spring.application.name=SpringBootBackend
#configure server port with different id
server.port=2026
#configure db properties
spring.datasource.url=jdbc:h2:file:./data/wellcampusdb;NON_KEYWORDS=USER,DAY,DATE,TIME,ROLE,YEAR,MONTH
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
#configure hibernate and jpa properties
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update